version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.1
  # shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
          exclude: RC006,RC009
      # - shellcheck/check:
      #     exclude: SC2148,SC2038,SC2086,SC2002,SC2016
      #     filters: *filters
      - orb-tools/publish:
          orb-name: smaeda-ks/orb-hashicorp-vault-cli
          vcs-type: << pipeline.project.type >>
          requires:
            [orb-tools/lint, orb-tools/review, orb-tools/pack]
          # Use a context to hold your publishing token.
          context: orb-publishing
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          config-path: .circleci/test-deploy.yml
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires: [orb-tools/publish]
          filters: *filters
